name: Terraform Deployment

on:
  push:
    branches: [ main ]
    paths:
      - terraform/**
jobs:
  terraform:
    name: terraform test
    runs-on: ubuntu-latest

  #branch checkout
    steps:
      - name: test
        run: |
          ls -al