name: Terraform Deployment

on:

  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - terraform/**

jobs:
  terraform:
    name: terraform Infra
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false

      - name: AWS Configs
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-west-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform init
        id: init
        working-directory: ./terraform
        run: |
          terraform init  
        #-backend-config="backend.tf" -input=false
        
      - name: Terraform plan
        id: plan
        working-directory: ./terraform
        run: |
          terraform plan -var-file=./configs/staging.tfvars -input=false

      - name: Terraform apply
        if: github.ref == 'refs/heads/main'
        id: apply
        working-directory: ./terraform
        run: |
          terraform apply -var-file=./configs/staging.tfvars -input=false