name: Terraform Deployment

on:
  push:
    branches: [ main ]
    paths:
      - terraform/**
jobs:
  terraform:
    name: terraform test
    runs-on: ubuntu-latest

  #branch checkout
    env: 
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws-region: us-west-2
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false
      # - name: Switch to terraform Dir
      #   run: |
      #     cd terraform
      - name: Terraform init
        id: init
        run: |
          cd terraform
          terraform init -upgrade=true -no-color -input=false
      - name: Terraform plan
        id: plan
        run: |
          cd terraform
          terraform plan -var-file=./configs/staging.tfvars -no-color -input=false